from typing import Dict, Optional

import torch
from torch.utils.data import Dataset

from .geometry import (
    healpix_unit_vectors,
    logmap,
    random_rotation,
    rotate_points,
    tangent_basis,
)


def analytic_sphere_texture(points: torch.Tensor) -> torch.Tensor:
    """A deterministic textured RGB-like signal on the sphere."""
    x, y, z = points.unbind(dim=-1)
    c0 = 0.5 + 0.5 * torch.sin(7.0 * x + 3.0 * y - 2.0 * z)
    c1 = 0.5 + 0.5 * torch.sin(-4.0 * x + 6.0 * y + 5.0 * z)
    c2 = 0.5 + 0.5 * torch.cos(5.0 * x - 2.0 * y + 8.0 * z)
    return torch.stack([c0, c1, c2], dim=-1)


class SyntheticRotationFlowDataset(Dataset):
    """Synthetic HEALPix optical-flow pairs generated by known 3D rotations.

    Frame 1 is a fixed analytic texture on sphere points p. Frame 2 is the same
    texture after a random global rotation R, so the ground-truth correspondence
    for p is R p.
    """

    def __init__(
        self,
        resolution: int,
        length: int = 128,
        max_angle_deg: float = 5.0,
        seed: int = 13,
        dtype: torch.dtype = torch.float32,
    ) -> None:
        self.resolution = resolution
        self.length = length
        self.max_angle_deg = max_angle_deg
        self.seed = seed
        self.points = healpix_unit_vectors(resolution, dtype=dtype)
        self.basis_east, self.basis_north = tangent_basis(self.points)
        self.frame1 = analytic_sphere_texture(self.points)

    def __len__(self) -> int:
        return self.length

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        generator = torch.Generator(device="cpu")
        generator.manual_seed(self.seed + idx)

        axis, angle = random_rotation(
            generator,
            self.max_angle_deg,
            device=torch.device("cpu"),
            dtype=self.points.dtype,
        )

        endpoint = rotate_points(self.points, axis, angle)
        inverse_points = rotate_points(self.points, axis, -angle)
        frame2 = analytic_sphere_texture(inverse_points)
        flow = logmap(self.points, endpoint, self.basis_east, self.basis_north).squeeze(0)

        return {
            "frame1": self.frame1.clone(),
            "frame2": frame2,
            "flow": flow,
            "endpoint": endpoint,
            "axis": axis,
            "angle": angle.unsqueeze(0),
        }


class SyntheticRotationFlowDatasetFromPoints(Dataset):
    """Synthetic optical-flow pairs on caller-provided sphere samples."""

    def __init__(
        self,
        points: torch.Tensor,
        length: int = 128,
        max_angle_deg: float = 5.0,
        seed: int = 13,
    ) -> None:
        if points.ndim != 2 or points.size(-1) != 3:
            raise ValueError("points must have shape [N, 3]")
        self.length = length
        self.max_angle_deg = max_angle_deg
        self.seed = seed
        self.points = points.detach().cpu()
        self.basis_east, self.basis_north = tangent_basis(self.points)
        self.frame1 = analytic_sphere_texture(self.points)

    def __len__(self) -> int:
        return self.length

    def __getitem__(self, idx: int) -> Dict[str, torch.Tensor]:
        generator = torch.Generator(device="cpu")
        generator.manual_seed(self.seed + idx)

        axis, angle = random_rotation(
            generator,
            self.max_angle_deg,
            device=torch.device("cpu"),
            dtype=self.points.dtype,
        )

        endpoint = rotate_points(self.points, axis, angle)
        inverse_points = rotate_points(self.points, axis, -angle)
        frame2 = analytic_sphere_texture(inverse_points)
        flow = logmap(self.points, endpoint, self.basis_east, self.basis_north).squeeze(0)

        return {
            "frame1": self.frame1.clone(),
            "frame2": frame2,
            "flow": flow,
            "endpoint": endpoint,
            "axis": axis,
            "angle": angle.unsqueeze(0),
        }


def make_single_rotation_pair(
    resolution: int,
    angle_deg: float,
    axis: Optional[torch.Tensor] = None,
    dtype: torch.dtype = torch.float32,
) -> Dict[str, torch.Tensor]:
    points = healpix_unit_vectors(resolution, dtype=dtype)
    basis_east, basis_north = tangent_basis(points)
    if axis is None:
        axis = torch.tensor([0.2, 0.4, 1.0], dtype=dtype)
    axis = axis / axis.norm().clamp_min(1e-8)
    angle = torch.tensor(angle_deg * torch.pi / 180.0, dtype=dtype)

    endpoint = rotate_points(points, axis, angle)
    inverse_points = rotate_points(points, axis, -angle)
    return {
        "frame1": analytic_sphere_texture(points),
        "frame2": analytic_sphere_texture(inverse_points),
        "flow": logmap(points, endpoint, basis_east, basis_north).squeeze(0),
        "endpoint": endpoint,
        "points": points,
    }
